### ISSUE TITLE
Duplication of attribute title

### ISSUE THREAD

**Issue by hoanguel** [loveorigami/yii2-bootstrap-toggle#2]
I just try this extension but when using active form it printed twice the label of the model attribute. Could you please check? Thanks!
![toogle](https://cloud.githubusercontent.com/assets/4293147/15112120/a07edc1c-15db-11e6-98d2-18486209f934.jpg)

**Comment by loveorigami** [comment]
Try with options

``` php
'options' => [
.......
  'label' => false,
  'inline' => false,
],
```

**Comment by hoanguel** [comment]
Thanks, it works! Shouldn't these be default values?

**Comment by loveorigami** [comment]
ok. I am added label option to false
https://github.com/loveorigami/yii2-bootstrap-toggle/blob/master/Toggle.php#L52
